name: Rename Package

on:
  workflow_call:
    inputs:
      package-name:
        type: string
      company-name:
        type: string

jobs:
  rename:
    name: Rename
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3        
