name: Rename Package

on:
  workflow_call:
    inputs:
      package-name:
        type: string
        required: true
      company-name:
        type: string
        required: true
      official-name:
        type: string
        required: false

permissions:
  contents: write

jobs:
  rename:
    name: Rename
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get full package name
        id: package-name
        run: |
          NAME=$(echo "${{ inputs.official-name }}" | tr '[:upper:]' '[:lower:]')

          if [ -z "$NAME" ]; then
            NAME=$(echo com."${{ inputs.company-name }}"."${{ inputs.package-name }}" | tr '[:upper:]' '[:lower:]' | sed 's/ //g')
            echo "Official package name was not provided, '$NAME' will be used instead"
          fi

          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Edit package name
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: name
          value: ${{ steps.package-name.outputs.name }}

      - name: Edit package display name
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: displayName
          value: ${{ inputs.package-name }}

      - name: Rename assembly definition files
        id: rename-asmdef
        run: |
          function rename_asmdef_in_directory() {
            local DIRECTORY="$1"

            if ! [ -d "$DIRECTORY" ]; then
              echo "Notice: Directory expected to contain a '.asmdef' file, '$DIRECTORY' does not exits." >&2
              return
            fi
            
            local CURRENT_PATH=$(find "$DIRECTORY" -maxdepth 1 -name "*.asmdef" -print -quit)
            echo $CURRENT_PATH
            if ! [ -d "$CURRENT_PATH" ]; then
              echo "Notice: Expected '.asmdef' files was not found in directory '$DIRECTORY'." >&2
              return
            fi

            local NEW_NAME="$2"
            local NEW_PATH=$(dirname "$CURRENT_PATH")/NEW_NAME

            mv $CURRENT_PATH $NEW_PATH
            echo "Renamed '$CURRENT_PATH' to '$NEW_PATH'." >&2

            echo $NEW_PATH
          }
          
          ASMDEF_BASE_NAME=$(echo "${{ inputs.company-name }}"."${{ inputs.package-name }}" | sed 's/ //g')

          echo "runtime=$(rename_asmdef_in_directory "Runtime" "$ASMDEF_BASE_NAME")" >> "$GITHUB_OUTPUT"
          echo "editor=$(rename_asmdef_in_directory "Editor" "$ASMDEF_BASE_NAME.Editor")" >> "$GITHUB_OUTPUT"
          echo "runtime-tests=$(rename_asmdef_in_directory "Tests/Runtime" "$ASMDEF_BASE_NAME.Tests")" >> "$GITHUB_OUTPUT"
          echo "editor-tests=$(rename_asmdef_in_directory "Tests/Editor" "$ASMDEF_BASE_NAME.Editor.Tests")" >> "$GITHUB_OUTPUT"

      - name: Update Runtime assembly definition name
        if: steps.rename-asmdef.outputs.runtime != ''
        uses: jossef/action-set-json-field@v2
        with:
          file: ${{ steps.rename-asmdef.outputs.runtime }}
          field: name
          value: "${{ inputs.company-name }}.${{ inputs.package-name }}"

      - name: Update Editor assembly definition name
        if: steps.rename-asmdef.outputs.editor != ''
        uses: jossef/action-set-json-field@v2
        with:
          file: ${{ steps.rename-asmdef.outputs.editor }}
          field: name
          value: "${{ inputs.company-name }}.${{ inputs.package-name }}.Editor"

      - name: Update Runtime Tests assembly definition name
        if: steps.rename-asmdef.outputs.runtime-tests != ''
        uses: jossef/action-set-json-field@v2
        with:
          file: ${{ steps.rename-asmdef.outputs.runtime-tests }}
          field: name
          value: "${{ inputs.company-name }}.${{ inputs.package-name }}.Tests"

      - name: Update Editor Tests assembly definition name
        if: steps.rename-asmdef.outputs.editor-tests != ''
        uses: jossef/action-set-json-field@v2
        with:
          file: ${{ steps.rename-asmdef.outputs.editor-tests }}
          field: name
          value: "${{ inputs.company-name }}.${{ inputs.package-name }}.Editor.Tests"
